dtb-$(CONFIG_ARCH_EXYNOS7) += exynos7-espresso.dtb

dtb-$(CONFIG_MODEL_GREATLTE) += exynos8895-greatlte_eur_open_00.dtb exynos8895-greatlte_eur_open_01.dtb exynos8895-greatlte_eur_open_02.dtb exynos8895-greatlte_eur_open_03.dtb exynos8895-greatlte_eur_open_05.dtb exynos8895-greatlte_eur_open_06.dtb exynos8895-greatlte_eur_open_07.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
